apps/blog/urls.py
from django.urls import path, include
from apps.blog.views import list_page, blog_details
app_name = 'blog'
urlpatterns = [
    path('', list_page, name='list_page'),
    path('details/<slug>/', blog_details, name='blog_details'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls')),
    path('order/', include('apps.order.urls')),
    path('blog/', include('apps.blog.urls')),
    path('uploads/', include('ckeditor_uploader.urls')),
]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
]

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.website.models import BaseModel
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from ckeditor.fields import RichTextField

# Create your models here.
class Category(BaseModel):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Post(BaseModel):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    content =  RichTextField(verbose_name='Content')
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category, related_name='posts')
    featured_image = models.ImageField(upload_to='blog_images/', blank=True, null=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        ordering = ['-create_time']

    def save(self, *args, **kwargs):
        if not self.slug:
            # Generate a slug from the title and append a random string to ensure uniqueness
            self.slug = slugify(self.title) + '-' + get_random_string(length=4)
            # Check if the slug is unique, if not, regenerate until it is unique
            while Post.objects.filter(slug=self.slug).exists():
                self.slug = slugify(self.title) + '-' + get_random_string(length=4)
        super(Post, self).save(*args, **kwargs)


    def __str__(self):
        return self.title

apps/blog/views.py
from django.shortcuts import render
from apps.blog.models import Post
from apps.website.models import NavigationItem, Preference


# Create your views here.
def list_page(request):

    top_level_items = NavigationItem.objects.filter(parent__isnull=True).prefetch_related('children')
    preference = Preference.objects.filter(is_active=True).first()
    blogs = Post.objects.filter(is_published=True)
    
    return render(request, 'blog_list.html', { 'preference': preference,'navigation_items': top_level_items, 'blogs': blogs })



def blog_details(request, slug):

    top_level_items = NavigationItem.objects.filter(parent__isnull=True).prefetch_related('children')
    preference = Preference.objects.filter(is_active=True).first()
    post = Post.objects.get(slug=slug)

    return render(request, 'blog_details.html', { 'preference': preference,'navigation_items': top_level_items,'post': post })

apps/blog/templates/blog_details.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    /* Additional custom styles can be added here */
</style>
{% endblock %}

{% block main_content %}
<div class="w-full">
    <!-- Blog Post -->
    <section class="px-4 py-8 mx-auto lg:py-10 lg:px-6">
        <div class="max-w-screen-xl mx-auto space-y-8 lg:space-y-6 mt-10">
            <!-- Hero Image -->
            <!-- <img class="w-full object-cover h-64 md:h-48 lg:h-64" src="{{ post.featured_image.url }}" alt="Blog Hero Image"> -->
            <div class="flex justify-center">
                <img class="object-contain" src="{{ post.featured_image.url }}" alt="Blog Hero Image">
            </div>
            <!-- Content -->
            <div class="p-10">
                <!-- Title -->
                <h2 class="text-3xl font-bold text-gray-800 mb-4">{{ post.title }}</h2>
                <!-- Meta Information -->
                <div class="flex items-center text-sm text-gray-600 mb-4">
                    <div class="">
                        {% for category in post.categories.all %}
                        <span class="bg-gray-200 rounded-full py-1 px-3 text-sm text-gray-700 mr-2">{{ category.name }}</span>
                        {% endfor %}
                    </div>
                    <span>&nbsp;</span>
                    <span><i class="far fa-clock"></i>&nbsp;{{ post.create_time }}</span>
                </div>
                <!-- Post Content -->
                <p class="text-gray-700">
                    {{ post.content | safe }}
                </p>
            </div>
        </div>
    </section>
</div>
{% include 'footer.html' %}
{% endblock %}

apps/blog/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<style>
    /* Additional custom styles can be added here */
</style>
{% endblock %}

{% block main_content %}
<div class="w-full">
    <!-- Blog Post -->
    <section class="px-4 py-8 mx-auto lg:py-10 lg:px-6">
        <div class="max-w-screen-xl mx-auto space-y-8 lg:space-y-6 mt-10">
    
            <div class="flex flex-wrap items-center justify-center lg:justify-between mt-5 mb-5">
                {% for post in blogs %}
                    <a href="{% url 'blog:blog_details' slug=post.slug %}" class="mt-4">
                        <div
                            class="max-w-sm bg-white border border-gray-200 rounded-lg shadow">
    
                            <img class="rounded-t-lg" src="{{post.featured_image.url}}" alt="" />
    
                            <div class="p-5">
    
                                <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
                                    {{post.title}}
                                </h5>
                                <div class="">
                                    {% for category in post.categories.all %}
                                    <small class="bg-gray-200 rounded-full py-1 px-3 text-sm text-gray-700 mr-2 mt-2">
                                        {{ category.name}}
                                    </small>
                                    {% endfor %}
    
                                </div>
                                <p class="mb-3 font-normal text-gray-700">{{post.content|safe|slice:100}}</p>
                                <p class="mt-1"><small><i class="fa-regular fa-clock"></i>&nbsp;{{post.create_time}}</small></p>
    
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    
    </section>
</div>

{% endblock %}